version: "3.4"

services:
  bartender-frontend:
    container_name: bartender-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VUE_APP_BACKEND_URL="https://horecarobot-frontend.azurewebsites.net/"
    ports:
      - "8081:80"
