name: CI

on:
  push:
    branches:
      - '*'

jobs:
  Unit_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Setup Docker
      run: docker compose up --build -d

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

   - name: Push to Docker Hub
     run: |
     docker build -t iqfx/horeca-frontend:latest .
     docker push iqfx/horeca-frontend:latest